### ISSUE TITLE
Invenio installation problems

### ISSUE THREAD

**Issue by sergejzr** [inveniosoftware/helm-invenio#18]
Good day,
I am just about to install Invenio on our servers and encopuntered a problem when executing:

```
helm repo add helm-invenio https://github.com/inveniosoftware/helm-invenio
Error: looks like "https://github.com/inveniosoftware/helm-invenio" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/inveniosoftware/helm-invenio/index.yaml : 404 Not Found
```

Seems that the page https://inveniosoftware.github.io/helm-invenio/ does not exist.

**Comment by lindhe** [comment]
Same for me!

```console
$ helm repo add helm-invenio https://inveniosoftware.github.io/helm-invenio/
Error: looks like "https://inveniosoftware.github.io/helm-invenio/" is not a valid chart repository or cannot be reached: failed to fetch https://inveniosoftware.github.io/helm-invenio/index.yaml : 404 Not Found
```

**Comment by lindhe** [comment]
The Helm chart is not published online. Currently, the only way to install this chart is to clone this repo and install it from disk.

Work to implement versioning and to publish the chart will be tracked in #133 .

Marking this as closed, since it's not expected to work until the chart is published.
